<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" />
        <PackageVersion Include="SecretAPI" Version="3.1.1" />
        <PackageVersion Include="SecretLabNAudio.Core" Version="2.0.0" />
    </ItemGroup>

</Project>