name: Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:

  release:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: Axwabo/scpsl-references-downloader@v1

      - name: Build
        run: dotnet build -c Release -o Output

      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: Output/ScpProximityChat*.dll,Output/ScpProximityChat*.xml
